feat: add canonical link setup
fleek-platform/website pull request #266
Opened 2024-10-15 15:41 UTC by tobySolutions

## Why?

This pull request automates the addition of the canonical meta tag to every page within the website using the `<link/>` tag.

## How?

- For the docs pages, make sure the slugs passed down to the layout code to ensure appropriation of the URLs.
- Used the custom function ` generateCanonicalUrl(baseUrl: string, slug?: string)` to handle canonical URLs for the base layouts

## Tickets?

- [Self-referencing Canonical tags](https://linear.app/fleekxyz/issue/MKTG-234/self-referencing-canonical-tags)

## Contribution checklist?

- [x] The commit messages are detailed
- [x] The `build` command runs locally
- [x] Assets or static content are linked and stored in the project
- [x] Document filename is named after the slug
- [x] You've reviewed spelling using a grammar checker
- [x] For documentation, guides or references, you've tested the commands and steps
- [x] You've done enough research before writing

## Security checklist?

- [x] Sensitive data has been identified and is being protected properly
- [x] Injection has been prevented (parameterized queries, no eval or system calls)
- [x] The Components are escaping output (to prevent XSS)

2024-10-15 17:12 UTC, heldrida commented on src/utils/generateCanonicalUrl.ts
> +  if (slug === 'docs/') {
Is this required? This will overwrite as `docs` which then will be written as `docs/` it seems

2024-10-15 17:38 UTC, gabrielmpinto commented on src/utils/generateCanonicalUrl.ts
> +  if (slug === 'docs/') {
Trailing slashes are usually a server side setting, don't know what's being used here though.

But if we can't change that, shouldn't this method just be appending `/` to all strings that don't end in `/`? Why does this only apply to docs?

2024-10-15 17:38 UTC, heldrida commented on src/utils/generateCanonicalUrl.ts
> +  if (slug === 'docs/') {
@nlc616 the instruction here is precisely the opposite, it checks for "docs/" (notice the slash) and returns `baseUrl/slug`, e.g. for a slug "docs/" it returns "https://fleek.xyz/docs".

2024-10-15 17:50 UTC, heldrida commented on src/utils/generateCanonicalUrl.ts
> +  if (slug === 'docs/') {
@nlc616 I've moved this discussion internally. Due to server.

2024-10-15 20:38 UTC, sharad-s submitted a review, later dismissed

2024-10-16 07:58 UTC, heldrida commented on src/utils/generateCanonicalUrl.ts
> +  return `${baseUrl}/${slug.replace(/^\/|\/$/g, '')}/`;
The variable "slug" here should be sanitized to allow you to make any canonical URL contain a trailing slash. E.g. remove any invalid symbol such as "slashes", after join baseUrl + slug + trailing slash.

2024-10-16 07:58 UTC, heldrida commented on src/layouts/DocsHtml.astro
> +  </head><body
```suggestion
  </head>
<body
```

2024-10-16 08:00 UTC, heldrida commented on src/layouts/BaseHtml.astro
> +const contentSlug = ogMeta?.slug || Astro.url.pathname;
The fallback to pathname might not correspond to a valid slug. Have you tested it?

2024-10-16 08:01 UTC, heldrida requested changes
See comments and internal discussion

2024-10-16 08:02 UTC, tobySolutions commented on src/layouts/BaseHtml.astro
> +const contentSlug = ogMeta?.slug || Astro.url.pathname;
Yes, this works actually. I tested it out. It is meant to capture cases of pages like those within the `legal` content directory that are just markdown content being rendered as pages.

2024-10-16 08:26 UTC, tobySolutions commented
> See comments and internal discussion

Thank you 🫡

2024-10-16 08:44 UTC, heldrida requested changes

2024-10-16 08:44 UTC, heldrida commented on src/utils/generateCanonicalUrl.ts
> +    .join('/');
You can simplify it without regex and this encode URI (this will defeat your purpose as it'll transform chars by unwanted characters).

```suggestion
  const sanitizedSlug = slug
    .trim()
    .split('/')
    .filter(item => item)
    .join('/');
```

2024-10-16 08:44 UTC, heldrida commented on src/utils/generateCanonicalUrl.ts
> +  const cleanBaseUrl = baseUrl.replace(/\/$/, '');
The baseUrl is something we control. If you really need to validate our input, look into the `getSiteUrl` in `src/utils/url.ts`, throw an error upfront if the admin placed an unexpected URL format. Finally, you can remove need to pass a "baseUrl" as you can get it upfront. Something like the following or use the getSiteUrl in the function body:

```
const BASE_URL = getSiteUrl();

export function generateCanonicalUrl...
```

```suggestion
```

2024-10-16 09:04 UTC, heldrida approved these changes
@tobySolutions make sure to manually test it.

2024-10-16 09:05 UTC, tobySolutions commented
> @tobySolutions make sure to manually test it.

Sure thing!! 🙌

2024-10-16 09:06 UTC, merged