Feat/add support page
fleek-platform/website pull request #6
Opened 2024-06-06 21:59 UTC by tobySolutions

## Why?

Work here is for the new knowledge base that is being built within the new fleek.xyz/support since the Zendesk version will be deprecated soon, this will serve as the new knowledge base.

## How?

- Build out the UI and functionality such that it matches the new branding and has what the existing Zendesk support platform has

## Tickets?

- https://linear.app/fleekxyz/project/update-knowledge-center-0ea4a420ac02/overview

## Contribution checklist?

- [x] The commit messages are detailed
- [x] The `build` command runs locally
- [x] Assets or static content are linked and stored in the project
- [ ] Document filename is named after the slug
- [] You've reviewed spelling using a grammar checker
- [ ] For documentation, guides or references, you've tested the commands and steps
- [x] You've done enough research before writing

## Security checklist?

- [x] Sensitive data has been identified and is being protected properly
- [ ] Injection has been prevented (parameterized queries, no eval or system calls)
- [x] The Components are escaping output (to prevent XSS)

2024-06-07 19:39 UTC, KanishkKhurana commented
Awaiting code format check

2024-06-08 16:03 UTC, tobySolutions commented
> Awaiting code format check

Checking now.

2024-06-11 19:18 UTC, tobySolutions commented
> Converted PR to draft until we have the following features ready:
> -Submitting a support ticket
> -Submitting a feature request
> -Chatbot

Sounds good 🙌.

2024-06-21 09:13 UTC, heldrida requested changes

2024-06-21 09:13 UTC, heldrida commented on src/layouts/SupportPage.astro
> +    src="https://static.zdassets.com/ekr/snippet.js?key=c0ecb1c1-369a-4543-b528-cbba3f2fb35d"
The key should be placed in the main settings file.

2024-06-21 09:13 UTC, heldrida commented on src/pages/billing/[category].astro
> +const indexNameBilling = import.meta.env
This would be a "billing" index. Also, reminder "troubleshooting" shouldn't exist but "references".

2024-06-21 09:13 UTC, heldrida commented on src/pages/troubleshooting.astro
We should use the references, no need for a new category

2024-06-21 09:13 UTC, heldrida commented on src/styles/supportPage.css
> +  top: 50% !important;
If you need to use !important it seems that there are issues. You can increase specificity in the selector and remove !important.

For example, if you have a parent wrapper  named foobar for "swiper"

```css
.foobar {
  .swiper {
     width: 100%;
     ...
  }
}
```

2024-06-21 09:13 UTC, heldrida commented on src/utils/url.ts
> +  }
Fix the redundancy. We shouldn't have to true is true, and false is false.

```suggestion
 return path?.includes(string);
```

2024-06-24 18:32 UTC, tobySolutions commented on public/images/article-img.svg
Should I take it off instead?

2024-06-24 18:41 UTC, tobySolutions commented on public/images/article-img.svg
Already removed.

2024-06-24 19:14 UTC, tobySolutions commented on src/content/billing/billing/I-have-an-issue-with-billing-I-need-help/dns-fleek.png
Thank you for this clarification, I was trying to adapt to the categorization from Zendesk.

2024-06-25 10:14 UTC, heldrida requested changes

2024-06-25 10:14 UTC, heldrida commented on src/pages/billing.astro
> +const pageTitle = 'billing';
```suggestion
```

2024-06-25 10:14 UTC, heldrida commented on src/pages/billing/[...slug].astro
> +const back = () => {};
Doesn't seem to be used.

```suggestion
```

2024-06-25 10:14 UTC, heldrida commented on src/pages/billing/[...slug].astro
> +  document.getElementById('goBackButton')?.addEventListener('click', () => {
Seems that this would fail for a user who lands in the content page from a twitter link, discord or google search? I don't have access to the user flow, but if the go back should always go back to /billing then might as well just make go back link directly there semantically and no need for js.

2024-06-25 10:14 UTC, heldrida commented on src/pages/billing/[category].astro
> +const pageTitle = 'Billing';
```suggestion
```

2024-06-25 10:14 UTC, heldrida commented on src/pages/guides/[...slug].astro
> +    <div class="mb-10 w-fit" onclick="history.back()">
Relates to previous comment regarding where the user lands from; which can be determined that if a user is in a sub page of /guides it can go back to /guides semantically, no need for js. I don't have the user flow here, but do check.

⚠️ Also, these go back buttons are out of the scope for this task.

2024-06-25 10:14 UTC, heldrida commented on src/pages/references/[...slug].astro
> +      <ButtonGray className="flex items-center justify-center gap-12 px-5">
Relates to previous comment regarding where the user lands from; which can be determined that if a user is in a sub page of /references it can go back to /references semantically, no need for js. I don't have the user flow here, but do check.

⚠️ Also, these go back buttons are out of the scope for this task.

2024-06-25 10:14 UTC, heldrida commented on src/settings.json
> +      },
References seem to be replacing "troubleshooting". So, it shouldn't exist here?

```suggestion
```

2024-06-25 10:14 UTC, heldrida commented on src/settings.json
> +    "zendeskKey": "c0ecb1c1-369a-4543-b528-cbba3f2fb35d",
Related to previous comment as it should have a sounder name to prevent future maintainers from declaring sensitive data, e.g. use public zendesk snippet key or similar

2024-06-25 10:14 UTC, heldrida commented on src/settings.json
> +        "pathName": "Home"
Relates to previous comment on name consistency, e.g. pathname

2024-06-25 10:14 UTC, heldrida commented on src/styles/supportPage.css
> +    @apply box-border min-h-screen pb-128 font-sans text-[1.5rem] text-[#ECEDEE];
no hard type colours please. applies elsewhere in file.

2024-06-25 11:19 UTC, tobySolutions commented on package.json
> +    "@types/katex": "^0.16.7",
I was using for a component I removed from the forms together with Suneditor, because, the flow changed. Should have uninstalled it.

2024-06-25 11:54 UTC, tobySolutions commented on src/components/Support/SupportMenu.tsx
> +              'text-[#2294ff]': getActivePath(item.path),
Regarding designs, I followed what I copied over from the Zendesk UI. I have made an update though, I have added the blue colors to the color palette and I have updated the :hover and :active states of the menu items to match the rest of the website.

2024-06-25 12:14 UTC, tobySolutions commented on src/components/Support/UsefulVideos.tsx
> +  const videoSrc = `${src}?enablejsapi=1&origin=https%3A%2F%2Fsupport.fleek.xyz&widgetid=${widgetId}'`;
No, widgetId is not a made-up attribute, it is a part of the embed code I took from Youtube and as such I added it as a dynamic value.

2024-06-25 12:25 UTC, tobySolutions commented on src/components/Support/form/NewRequestForm.tsx
> +        toast.error(data.error.issues[0].message);
This is a great suggestion actually

2024-06-25 13:26 UTC, tobySolutions commented on src/content/billing/I-have-an-issue-with-billing-I-need-help/dns-fleek.png
Yeah, I will request for these. I'll loop Royce in on it.

2024-06-25 13:28 UTC, tobySolutions commented on src/content/billing/I-have-an-issue-with-billing-I-need-help/index.md
> +desc: 'Our staff will manually process your request and reply back within 48 hours.'
Not sure if it is my place to make decisions on copy content, I will add placeholders there for now though

2024-06-25 13:32 UTC, tobySolutions commented on src/pages/billing.astro
> +const indexNameBilling = import.meta.env.PUBLIC_MEILISEARCH_INDEX_BILLING;
Oh ok, great!

2024-06-27 16:17 UTC, heldrida requested changes

2024-06-27 16:17 UTC, heldrida commented on src/content/references/common-issues/428-errors-on-custom-domain/index.md
> +---
Let's create a ticket to improve this for the end user. At the very least, it should include a brief reason why this is happening, what we are doing about it, and the link to the support path.

2024-06-28 09:38 UTC, tobySolutions commented on src/components/Support/config.ts
> +    widgetId: '1',
Done, I have removed all instances of the `widget_id`, it was a parameter that came with the iframe embed I got from Youtube, but, I just looked through the Youtube iframe docs and no such param exists.

2024-06-28 10:32 UTC, tobySolutions commented on src/content/references/common-issues/troubleshooting-ens-domains/index.md
> +  <source src="/support/troubleshooting/common-issues/ens-remove.mp4" type="video/mp4">
Actually, the reason I moved it to public was because when I placed the video in the same directory as the `troubleshooting-ens-domains`, the video was not loading up; I'll return it back there.

2024-06-28 11:24 UTC, tobySolutions commented on src/content/references/common-issues/428-errors-on-custom-domain/index.md
> +---
I will ask for Gonza's review on this.

2024-06-28 11:25 UTC, tobySolutions commented on src/content/references/common-issues/428-errors-on-custom-domain/index.md
> +---
I linked to the new request form though

2024-06-28 11:28 UTC, tobySolutions commented on src/content/references/common-issues/adding-domains-through-fleek-cli/index.md
> +---
I ported this over from Zendesk as part of the first milestone agreed upon with Nate, a lot of the content review here I assumed will be after this first PR.

I understand your concern and what you mean perfectly, but, I think Gonza and Guillaume will be best to make these fixes. What do you think? I can link to this though https://fleek.xyz/docs/cli/domains

2024-06-28 16:05 UTC, heldrida commented on src/settings.json
> +        "pathname": "Report a site"
This is not a valid "pathname", considering https://github.com/fleek-platform/website/pull/6/files#diff-aab4ceb6d3254a7b948f95d8057cd8d91cd43c09f95569885cbce6d8b079d926R57 which computes it, it'd always fail to match?

```js
"Report a site".includes("/requests/report-site");
pathname.includes(term);
```

Also, as it stands the term and pathname of the utility function https://github.com/fleek-platform/website/pull/6/files#diff-aab4ceb6d3254a7b948f95d8057cd8d91cd43c09f95569885cbce6d8b079d926R57, at very least, should have both normalized (e.g. to lowercase) for a actual URI comparison.

2024-06-28 16:05 UTC, heldrida commented on src/settings.json
> +        "pathname": "Submit a request"
See previous comment

2024-06-30 03:29 UTC, tobySolutions commented on .github/actions/spell-checker/ignore_words.txt
> +Cloudflare's
Oh ok, awesome!

2024-06-30 03:37 UTC, tobySolutions commented on src/components/Support/form/ui/Tooltip.tsx
> +            fill="#61a5ff"
It is a new color, and, copied over according to design from the old support website. I will do this for now, but, once all is done; I will show work done on the support center so far and ask for a review of things.

2024-06-30 03:41 UTC, tobySolutions commented on src/content/references/best-practices-for-building-ipfs-hosted-websites/index.md
>  IPFS-hosted websites are gaining popularity as a way to host your site. Although the technology is still early, there's been some significant progress and it's an exciting to see fully fledged applic
Sure thing, this makes total sense. Taking it off now.

2024-06-30 03:52 UTC, tobySolutions commented on src/settings.json
> +        "pathname": "Report a site"
Oh no, you actually have it wrong. The `pathname` I am using is the URL path gotten from `Astro`, not the `pathname` from the `supportName` object. I  will rename the former to a more suitable name now.

2024-06-30 03:56 UTC, tobySolutions commented on src/settings.json
> +        "pathname": "Report a site"
I have made fixes and the prop is now called `currentPagePath`

2024-06-30 04:01 UTC, tobySolutions commented on src/content/billing/I-have-an-issue-with-billing-I-need-help/index.md
> +---
Thank you for these. I will loop Gonza in on this to take a look and make fixes.

2024-07-03 10:14 UTC, heldrida commented on src/layouts/BaseHtml.astro
> +    }
The secondary menu is not of the base layout concern. Thus, we can move this requirement into the context of nav.

Example, here we hide any implementation details and keep it lean:

```suggestion
    <Nav client:load pathname={Astro.url.pathname} isSupportCenter />
```

In `@components/Nav`, we'd have:

```js
// You can move this as an utility function, see "@utils"
const supportMenuItems = settings.support.supportMenu.map(item => item.path.split('/')[1]);
const uniqueMenuItems = [...new Set(supportMenuItems)];
const hasSecondaryMenu = uniqueMenuItems.some(keyword => pathname.includes(keyword));
```

What we did here is to use the information we set in the configuration settings file and not duplicate or hard-type it elsewhere which is hard to maintain. This is because the settings is where we declare what is "support menu".

Finally, the `@components/Nav` would have

```js
    {
      hasSecondaryMenu && (
        <SupportMenu client:load currentPagePath={currentPagePath} />
      )
    }
```

Effectively deprecating need to create currentPagePath, hasSecondaryMenu and everything else in the base layout which shouldn't be concerned with any of it.

2024-07-03 10:14 UTC, heldrida commented on src/layouts/BaseHtml.astro
> +  currentPagePath.includes('requests');
See comment below, as none of this is base layout concern.

```suggestion
```

2024-07-03 10:15 UTC, heldrida commented on src/layouts/BaseHtml.astro
> +import SupportMenu from '@components/Support/SupportMenu';
See comment below.

```suggestion
```

2024-07-03 10:21 UTC, tobySolutions commented on src/settings.json
> +        "pathname": "Report a site"
All done, thank you.

2024-07-03 10:23 UTC, tobySolutions commented on src/content/references/faq/deploy-fails-with-no-error-message-after-switching-github-settings/index.md
> +If the above still didn't solve your issue, please open a support ticket for fleek.co and we will fix this for you. You will need to provide your site's fleek url ( for example, "burning-hall-9201.on
We are supposed to do away with all fleek.co references. I will fix all these.

2024-07-03 10:30 UTC, tobySolutions commented on src/components/Support/form/ui/Formtitle.tsx
Agree with this.

2024-07-04 17:33 UTC, heldrida commented on src/components/Support/form/SupportSearch.tsx
> +    [query],
You have a useCallback that is misused, as it only memoizes for "query" dependency. Notice that it would have to consider other several dependencies to operate correctly, e.g. "setLoading," "toast," etc. So, what you have written is an illusion.

2024-07-04 17:38 UTC, heldrida commented on src/components/Support/form/SupportSearch.tsx
> +    debounce(async (query: string) => {
Sorry mate, but this seems incorrect to me because the moment the debounce function is prepared and when triggered, it might show the wrong state. Since the debounced function might still be working with the old information as captured earlier, it won't reflect the correct state.

2024-07-04 17:48 UTC, heldrida commented on src/components/Support/form/SupportSearch.tsx
> +  const performSearch = useCallback(
Seems that this whole usecallback,debounce can be simplified by a simple lock state.

```
if (isLocked) return;

// Otherwise do what it has to do and set isLocked state to true
// when finish unlock
```

2024-07-05 08:41 UTC, heldrida requested changes

2024-07-05 08:41 UTC, heldrida commented on Services/ZenDesk/api.ts
> +      name: z.string().min(2),
You seem to have overridden the base decision. As "name" is now not required, this should be set as optional.

```suggestion
      name: z.string().min(2).optional(),
```

2024-07-05 13:36 UTC, heldrida approved these changes

2024-07-05 13:54 UTC, merged