style: add support center UX test feedback fixes
fleek-platform/website pull request #74
Opened 2024-07-11 08:19 UTC by tobySolutions

## How?

Add fixes for all the feedback given by @nlc616 after testing the support center in staging here: https://fleek-xyz-staging.on-fleek.app/requests/new by going through each and every of the issues and applying fixes to them one after the other to improve the support center's UX.

## Tickets?

- [Ticket 1](the-ticket-url-here)
- [Ticket 2](the-ticket-url-here)
- [Ticket 3](the-ticket-url-here)

## Contribution checklist?

- [ ] The commit messages are detailed
- [ ] The `build` command runs locally
- [ ] Assets or static content are linked and stored in the project
- [ ] Document filename is named after the slug
- [ ] You've reviewed spelling using a grammar checker
- [ ] For documentation, guides or references, you've tested the commands and steps
- [ ] You've done enough research before writing

## Security checklist?

- [x] Sensitive data has been identified and is being protected properly
- [x] Injection has been prevented (parameterized queries, no eval or system calls)
- [x] The Components are escaping output (to prevent XSS)

## References?

Optionally, provide references such as links

## Preview?

Optionally, provide the preview url here

2024-07-11 16:45 UTC, heldrida commented on src/components/Support/form/NewRequestForm.tsx
> +    async function fetchHealthStatus() {
Declare the function outside the useEffect.

2024-07-11 16:54 UTC, heldrida commented on src/components/Support/form/ReportSiteForm.tsx
> +    async function fetchHealthStatus() {
This function is the same as used before. While you have a utility for this, it can be improved to include a callback on failure or success.

2024-07-11 16:54 UTC, heldrida commented on src/components/Support/form/ReportSiteForm.tsx
> +            disabled={!isHealthy}
See previous comments in regards to checkup process and presentation of form

2024-07-11 21:00 UTC, tobySolutions commented on src/components/Support/form/ReportSiteForm.tsx
> +    async function fetchHealthStatus() {
I made an improvement to the `fetchHealthStatus` function; please let me know if that was what you meant.

2024-07-12 08:19 UTC, heldrida requested changes
Remove the variable https://github.com/fleek-platform/website/blob/0720eb5a57242a04d19f1534c04dfbd0e5516be7/src/components/NavBar/config.ts#L3 and declare the `/support` path in the menu's config. So that everyone can test it.

2024-07-12 08:19 UTC, heldrida commented on src/components/Support/form/NewRequestForm.tsx
> +      toast.error('Failed to fetch health status. Please try again later.');
The user shouldn't be concerned by a "health status". As a user, imagine that you're reporting an issue and you'd face "Failed to fetch health status. Please try again later.". So, if the health checkup fails, we let know something happened and we want to do something about it.

```suggestion
      if (!healthStatus) {
         throw new Error('Health status failure')
      }
    } catch (error) {
       console.error(error.message);
        toast.error(
          'Our support system is currently experiencing issues. Please report this to our team.',
        );
```

2024-07-12 08:19 UTC, heldrida commented on src/components/Support/SupportUnavailable.tsx
> +            href="https://discord.gg/2ERTJAWF"
Don't hard type. Use the settings discord url https://github.com/fleek-platform/website/blob/develop/src/settings.json#L90

2024-07-12 08:19 UTC, heldrida commented on src/components/Support/form/ReportSiteForm.tsx
> +  const [isHealthy, setIsHealthy] = useState<boolean>(true);
See related comment above

2024-07-12 08:19 UTC, heldrida commented on src/components/Support/form/ReportSiteForm.tsx
> +      toast.error('Failed to fetch health status. Please try again later.');
See related comment above

2024-07-12 08:19 UTC, heldrida commented on src/styles/supportPage.css
> +      color: #2d2305;
Remember not to use hard-type colours; I've mentioned this to you many times. Use the colour palette, please https://github.com/fleek-platform/website/blob/0720eb5a57242a04d19f1534c04dfbd0e5516be7/tailwind.config.mjs#L42

2024-07-12 08:19 UTC, heldrida commented on src/styles/supportPage.css
> +      background-color: #ffff57;
Read related comment below

2024-07-12 08:34 UTC, tobySolutions commented on src/components/Support/form/NewRequestForm.tsx
> +      toast.error('Failed to fetch health status. Please try again later.');
Valid! Should have just duplicated this.

2024-07-12 08:43 UTC, tobySolutions commented on src/styles/supportPage.css
> +      color: #2d2305;
For this, I was under the impression that you were referring to only within my React components' styling as you did not make a note about any of the ones in the previous PR within CSS files.

2024-07-12 09:05 UTC, tobySolutions commented
> supportUrlDefault

Done!

2024-07-12 09:15 UTC, heldrida approved these changes

2024-07-12 09:15 UTC, heldrida commented on src/components/Support/form/SupportSearch.tsx
> +            <ul className="rounded-md search-results-list z-20 max-h-[250px] overflow-auto rounded-b-[12px] bg-gray-dark-3 p-[12px] text-[1.3rem] shadow-2xl">
Doesn't seem utilized?

```suggestion
            <ul className="rounded-md z-20 max-h-[250px] overflow-auto rounded-b-[12px] bg-gray-dark-3 p-[12px] text-[1.3rem] shadow-2xl">
```

2024-07-12 09:20 UTC, heldrida approved these changes

2024-07-12 09:30 UTC, merged