feat( support forms): add form validation and better error handling
fleek-platform/website pull request #88
Opened 2024-07-18 23:42 UTC by tobySolutions

## Why?

The validations for the form were not enough, a user could submit a form if they did not meet some requirements from the server and they would get an inaccurate and unhelpful error message.

## How?

- Introduce an `isDisabled` state to help handle the buttons disabled state until all form submission conditions have been met.
- Properly handle server response error and make sure the toast shows the appropriate error.

## Tickets?

- [Ticket 1](https://linear.app/fleekxyz/issue/AS-274/support-ui-shouldnt-allow-user-submitting-less-then-expected-number-of)

## Contribution checklist?

- [x] The commit messages are detailed
- [x] The `build` command runs locally
- [x] Assets or static content are linked and stored in the project

## Security checklist?

- [x] Sensitive data has been identified and is being protected properly
- [x] Injection has been prevented (parameterized queries, no eval or system calls)
- [x] The Components are escaping output (to prevent XSS)

2024-07-19 08:28 UTC, heldrida requested changes

2024-07-19 08:28 UTC, heldrida commented on src/components/Support/form/NewRequestForm.tsx
> +      setIsButtonDisabled(value.trim().length < 30);
Only update state when required.  Not on every user char input.

```suggestion
      const shouldBeDisabled = value.trim().length < 30;

      if (shouldBeDisabled !== isButtonDisabled) {
        setIsButtonDisabled(shouldBeDisabled);
      }
```

2024-07-19 08:28 UTC, heldrida commented on src/components/Support/form/NewRequestForm.tsx
> +        <Button isDisabled={isButtonDisabled} />
This approach is ok, but form validation usually lets the user know what's going on, e.g. your comment must be at least X characters.

2024-07-19 08:28 UTC, heldrida commented on src/components/Support/form/utils.ts
> +    const errorMsg =
We prefer to show the user a sane error message, with a call to action, e.g. sorry/try again/let us know.
You can show the system error message as a console.error, but the user should get the descriptive-friendly version.

2024-07-19 08:33 UTC, tobySolutions commented on src/components/Support/form/NewRequestForm.tsx
> +        <Button isDisabled={isButtonDisabled} />
So, should I move in favor of that approach @heldrida?

2024-07-21 07:36 UTC, tobySolutions commented on src/components/Support/form/NewRequestForm.tsx
> +        <Button isDisabled={isButtonDisabled} />
Went down with that approach.

2024-08-06 12:54 UTC, heldrida requested changes

2024-08-06 12:54 UTC, heldrida commented on src/components/Support/form/NewRequestForm.tsx
> +    if (name === 'email' && !value.includes('@')) {
You can set the correct form input type and let the browser validate your email.

Example,

```
<form>
  <input type="email">
  <input type="submit" value="Submit">
</form>
```

Otherwise, you'd want to use regex to validate it. Here's an example https://emailregex.com

2024-08-06 12:54 UTC, heldrida commented on src/components/Support/form/NewRequestForm.tsx
> +    } else if (name === 'comment' && value.trim().length < 30) {
You must stop hard-typing the number of characters. You're sharing this value elsewhere.

In any case, the form validation can be done freely using HTML directives

For example for your `subject`

```
<input type="text" name="subject" required minlength="30" maxlength="180" />
```

2024-08-06 12:54 UTC, heldrida commented on src/components/Support/form/ReportSiteForm.tsx
> +    if (name === 'email' && !value.includes('@')) {
See previous relatable comments. In any case, if the functions were named the same, compute the same, there shouldn't be a reason to duplicate it. If HTML validation didn't exist,  and you'd have to stick with whichever you're trying here, you'd want to reuse the function.

2024-08-07 08:18 UTC, heldrida approved these changes

2024-08-07 08:21 UTC, merged